name: Deploy Changed Lambdas

on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_lambdas: ${{ steps.changes.outputs.changed_lambdas }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changes
        run: |
          changed_lambdas=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^lambdas/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "changed_lambdas=$changed_lambdas" >> $GITHUB_OUTPUT

  deploy-lambdas:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ${{ fromJson(needs.detect-changes.outputs.changed_lambdas) }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          cd lambdas/${{ matrix.lambda }}
          npm ci
      
      - name: Package lambda
        run: |
          cd lambdas/${{ matrix.lambda }}
          zip -r ../../fcn.zip .
      
      - name: Deploy lambda
        # env:
        #   CLIENT_ID: ${{ secrets.CLIENT_ID }}
        #   VIAX_USERNAME: ${{ secrets.VIAX_USERNAME }}
        #   VIAX_PASSWORD: ${{ secrets.VIAX_PASSWORD }}
        #   AUTH_URL: ${{ secrets.AUTH_URL }}
        #   API_URL: ${{ secrets.API_URL }}
        run: |
          echo "deployed"