name: Deploy to Viax

on:
  push:
    branches:
      - dev
    paths:
      - 'lambdas/**'  # Trigger on changes in the lambdas directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find and deploy modified lambdas
      run: |
        # Find the directories within lambdas/ that have been modified
        modified_lambdas=$(git diff --name-only ${{ github.sha }}~1 ${{ github.sha }} | grep '^lambdas/' | cut -d'/' -f 2 | sort -u)
        
        if [ -z "$modified_lambdas" ]; then
          echo "No Lambda functions were modified."
          exit 0
        fi

        for lambda in $modified_lambdas; do
          echo "Deploying Lambda: $lambda"
          cd lambdas/$lambda

          npm install
          npm version $(jq -r '.version' package.json)-${{ secrets.ENVIRONMENT }}.${{ github.run_number }}
          npm run build
          cp viax.${{ secrets.ENVIRONMENT }}.yaml viax.yaml
          npm run test
          rm -f fcn.zip
          npm install --production
          zip -r fcn.zip package.json viax.yaml src node_modules

          TOKEN=$(curl -X POST -d "grant_type=password&client_id=$CLIENT_ID&username=$VIAX_USERNAME&password=$VIAX_PASSWORD" $AUTH_URL | jq -r '.access_token')

          for i in {1..3}; do
            response=$(curl --request POST \
              --url "$API_URL" \
              --header "Authorization: Bearer $TOKEN" \
              --header 'Content-Type: multipart/form-data' \
              --form 'operations={ 
                "operationName": "upsertFunction",
                "query": "mutation upsertFunction($file: Upload!) { upsertFunction(input: { fun: $file }) { uid } }",
                "variables": { "file": null }
              }' \
              --form 'map={ "File":["variables.file"] }' \
              --form File=@./fcn.zip)
              
            if [[ $response == *"uid"* ]]; then
              echo "Successfully deployed Lambda function $lambda."
              break
            else
              echo "Failed to deploy Lambda function $lambda, retrying... ($i/3)"
              sleep 5
            fi
          done

          cd -  # Go back to the root directory for the next iteration
        done
