name: Deploy Changed Lambdas

on:
  push:
    branches:
      - dev
    paths:
      - 'lambdas/**'  # Trigger only when there are changes in the lambdas directory

jobs:
  find_changed_lambdas:
    runs-on: ubuntu-latest
    outputs:
      lambdas: ${{ steps.set_output.outputs.lambdas }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find modified Lambda paths
        id: set_output
        run: |
          echo "Finding modified Lambda paths..."
          # Get the list of changed directories in lambdas
          changed_dirs=$(git diff --name-only HEAD^ HEAD lambdas/ | grep '/$' | cut -d'/' -f2 | sort -u | jq -R . | jq -s .)
          echo "Changed lambdas: $changed_dirs"
          echo "::set-output name=lambdas::$changed_dirs"

  deploy:
    runs-on: ubuntu-latest
    needs: find_changed_lambdas
    strategy:
      matrix:
        lambda_path: ${{ fromJson(needs.find_changed_lambdas.outputs.lambdas) }}  # Get the changed lambda paths

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd lambdas/${{ matrix.lambda_path }}
          npm install

      - name: Build Lambda
        run: |
          cd lambdas/${{ matrix.lambda_path }}
          npm run build

      - name: Deploy Lambda
        run: |
          cd lambdas/${{ matrix.lambda_path }}
          # Add your deployment command here
          echo "Deploying Lambda from ${matrix.lambda_path}..."