name: Deploy Lambdas

on:
  push:
    branches:
      - dev
    paths:
      - 'lambdas/**'
  workflow_dispatch:
    inputs:
      lambda_name:
        description: 'Name of the lambda to deploy (use "all" to deploy all lambdas)'
        required: false
        type: string

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_lambdas: ${{ steps.changes.outputs.changed_lambdas }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changes
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.lambda_name }}" = "all" ]; then
              changed_lambdas=$(ls -d lambdas/* | cut -d'/' -f2 | jq -R -s -c 'split("\n")[:-1]')
            elif [ -n "${{ github.event.inputs.lambda_name }}" ]; then
              changed_lambdas='["${{ github.event.inputs.lambda_name }}"]'
            else
              changed_lambdas='[]'
            fi
          else
            changed_lambdas=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^lambdas/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "Changed lambdas: $changed_lambdas"
          echo "changed_lambdas=$changed_lambdas" >> $GITHUB_OUTPUT

  deploy-lambdas:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.changed_lambdas != '[]' }}
    strategy:
      matrix:
        lambda: ${{ fromJson(needs.detect-changes.outputs.changed_lambdas) }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Pre-deploy
        run: |
          cd lambdas/${{ matrix.lambda }}
          npm install
          npm version $(jq -r '.version' package.json)-${{ github.run_number }}
          npm run build
          cp viax.${GITHUB_REF_NAME}.yaml viax.yaml
          npm run test
          rm -f fcn.zip
          npm install --production
          zip -y -r fn.zip . 
      
      - name: Deploy lambda
        run: |
          echo "deployed"  #actual deploy code goes here.

  no-changes:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.changed_lambdas == '[]' }}
    steps:
      - name: No changes detected
        run: echo "No changes detected or no lambda specified. No deployment needed."